import NavbarComponent from "@/components/ui/navbar.component";
import type { Metadata } from "next";
import "./globals.css";
import "../node_modules/@glidejs/glide/dist/css/glide.core.min.css";
import FooterComponent from "@/components/ui/footer.component";

export const metadata: Metadata = {
  title: "KustomParts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent />
        <div>
          <div className="pb-[3.80rem]"></div>
          {children}
        </div>
        <FooterComponent />
      </body>
    </html>
  );
}
