import NavbarComponent from "@/components/ui/navbar.component";
import type { Metadata } from "next";
import "./globals.css";
import "../node_modules/@glidejs/glide/dist/css/glide.core.min.css";

export const metadata: Metadata = {
  title: "KustomParts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent />
        {children}
      </body>
    </html>
  );
}
